obj-m += holoram_kq.o

holoram_kq-y := \
	kernel/driver/holoram_dev.o \
	kernel/driver/holoram_queue.o \
	kernel/driver/holoram_ring.o \
	kernel/driver/holoram_mmap.o \
	kernel/driver/holoram_stats.o \
	kernel/policy/holoram_policy.o \
	kernel/policy/slot_budget.o \
	kernel/policy/channel_router.o
